# Generated by Django 2.2.4 on 2019-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_places', '0003_auto_20190902_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='formatted_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
