# Generated by Django 2.2.4 on 2019-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_places', '0004_auto_20190902_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='permanently_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
